#!/bin/sh
# Extract version from Debian changelog

VERSION=$(LC_ALL=C dpkg-parsechangelog | grep Version: | cut -d' ' -f2-)

cat >include/version.h <<EOF
/* This file is auto-generated by $0 */

#ifndef BILLBOARD_VERSION_H
#define BILLBOARD_VERSION_H

#define BILLBOARD_VERSION "$VERSION"

#endif /* BILLBOARD_VERSION_H */
EOF
